---
title: "Spécialités"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(RColorBrewer)
library(ggcpesrthemes)
theme_cpesr_setup(authors = "Julien Gossa", source = "Parcoursup (une formation BUT Informatique)")
```

```{r load}
matieres <- read.csv("matieres.csv", stringsAsFactors = TRUE)
specialites <- read.csv("specialites.csv")

bg21 <- read.csv("0671557D_BUT-Informatique_7967.csv",sep=";") %>%
  filter(Diplôme == "Bac en préparation", Série.diplôme == "Série Générale") %>%
  filter(Série.Domaine.Filière != "") %>%
  mutate_at(
    vars(starts_with("EDS.BAC.")),
    factor, levels = specialites$Spécialité, labels = specialites$Abréviation
  )

bg19 <- read.csv("0671557D_Info.2019.csv",sep=";") %>%
  filter(Diplôme == "Bac en préparation", Série.diplôme %in% c("Scientifique","Littéraire","Economique et social")) %>%
  filter(Série.Domaine.Filière != "") %>%
  mutate(Série.Domaine.Filière = factor(Série.Domaine.Filière, levels=c("S","ES","L")))
```

```{r bg19.cohorte.1.data, fig.width=10, fig.height=2}
df <- bg19 %>%
  group_by(Série.Domaine.Filière) %>%
  summarise(nombre = n())

all <- df %>% 
  transmute(
    bac = "Ancien Bac",
    categorisation = "Série",
    categorie = Série.Domaine.Filière,
    nombre = nombre)
```

- Nombre de groupes : `r nrow(df)`
- Taille des groupes : `r range(df$nombre)`

```{r bg19.cohorte.1.plot, fig.width=10, fig.height=2}
df %>%
  ggplot(aes(x=reorder(Série.Domaine.Filière,nombre),y=nombre,fill=Série.Domaine.Filière)) +
    geom_col() +
    coord_flip() +
    xlab("Série") + ylab("Nombre de candidatures") +
    guides(fill=FALSE) +
    ggtitle("Catégorisation des candidatures avec l'ancien Bac général (séries)") +
    theme_cpesr_cap() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
      )
```


```{r bg19.cohorte.2.data, fig.width=10, fig.height=3}
df <- bg19 %>%
  group_by(Série.Domaine.Filière, Spécialité.diplôme) %>%
  summarise(nombre = n()) %>%
  mutate(groupe = paste0(Série.Domaine.Filière,' (',Spécialité.diplôme,')'))

all <- bind_rows(
  all,
  df %>% transmute(
    bac = "Ancien Bac",
    categorisation = "Série + Spécialité",
    categorie = groupe,
    nombre = nombre)       
)
```

- Nombre de groupes : `r nrow(df)`
- Taille des groupes : `r range(df$nombre)`

```{r bg19.cohorte.2.plot, fig.width=10, fig.height=4}
df %>%
  ggplot(aes(x=reorder(groupe,nombre),y=nombre,fill=Série.Domaine.Filière)) +
    geom_col() +
    coord_flip() +
    facet_grid(Série.Domaine.Filière~., scales = "free_y", space = "free_y") +
    xlab("Série (Spécialité)") + ylab("Nombre de candidatures") +
    guides(fill=FALSE) +
    ggtitle("Catégorisation des candidatures avec l'ancien Bac général (séries + options)") +
    theme_cpesr_cap() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
      )
```

```{r bg21.cohorte.data, fig.width=10, fig.height=10}
df <- bg21 %>%
  mutate(groupe = paste0(EDS.BAC.Terminale," & ", EDS.BAC.Terminale.1)) %>%
  group_by(groupe) %>%
  summarise(nombre = n()) %>%
  mutate(groupe = reorder(groupe,nombre))
nb_groupes <- nrow(df)
palette_groupes <- rep(brewer.pal(8, "Dark2"),nb_groupes/8+1)[1:nb_groupes]

all <- bind_rows(
  all,
  df %>% transmute(
    bac = "Bac Blanquer",
    categorisation = "Spécialités de Terminale",
    categorie = groupe,
    nombre = nombre)
)
```

- Nombre de groupes : `r nrow(df)`
- Taille des groupes : `r range(df$nombre)`

```{r bg21.cohorte.1.plot, fig.width=10, fig.height=10}
df %>%
  ggplot(aes(x=groupe,y=nombre,fill=groupe)) +
    geom_col() +
    coord_flip() +
    scale_fill_manual(values=palette_groupes) +
    xlab("Spécialités de Terminale") + ylab("Nombre de candidatures") +
    guides(fill=FALSE) +
    ggtitle("Catégorisation des candidatures avec le nouveau Bac général (spécialités)") +
    theme_cpesr_cap() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
      )
```



```{r bg21.cohorte.2.data, fig.width=10, fig.height=15}
df <- bg21 %>%
  mutate(groupe = paste0(EDS.BAC.Terminale," & ", EDS.BAC.Terminale.1)) %>%
  mutate(options = case_when(
    Option.facultative.1.Scolarité == "" ~ "Aucune",
    Option.facultative.2.Scolarité == "" ~ Option.facultative.1.Scolarité,
    TRUE ~ paste0(Option.facultative.1.Scolarité, " & ",Option.facultative.2.Scolarité)
  )) %>%
  mutate(groupe.options = paste0(groupe," (", options,")")) %>%
  group_by(groupe, options, groupe.options) %>%
  summarise(nombre = n()) %>%
  group_by(groupe) %>%
  mutate(nombre.grp = sum(nombre)) %>%
  ungroup() %>%
  mutate(
    groupe = reorder(groupe,-nombre.grp),
    groupe.options = reorder(groupe.options,nombre.grp*1000+nombre))

all <- bind_rows(
  all,
  df %>% transmute(
    bac = "Bac Blanquer",
    categorisation = "Spécialités de Terminale + options",
    categorie = groupe.options,
    nombre = nombre)
)
```

- Nombre de groupes : `r nrow(df)`
- Taille des groupes : `r range(df$nombre)`

```{r bg21.cohorte.2.plot, fig.width=10, fig.height=20}
df %>%
  ggplot(aes(groupe.options,y=nombre,fill=groupe)) +
    geom_col() +
    coord_flip() +
    scale_fill_manual(values=rev(palette_groupes)) +
    facet_grid(groupe~., scales = "free_y", space = "free_y", labeller = label_wrap_gen(width=6)) +
    xlab("Spécialités (options)") + ylab("Nombre de candidatures") +
    guides(fill=FALSE) +
    ggtitle("Catégorisation des candidatures avec le nouveau Bac général (spécialités + options)") +
    theme_cpesr_cap() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
      )
```

```{r bg21.cohorte.3.data, fig.width=10, fig.height=40}
df <- bg21 %>%
  mutate(groupe = paste0(EDS.BAC.Terminale," & ", EDS.BAC.Terminale.1)) %>%
  mutate(options = case_when(
    Option.facultative.1.Scolarité == "" ~ "Aucune",
    Option.facultative.2.Scolarité == "" ~ Option.facultative.1.Scolarité,
    TRUE ~ paste0(Option.facultative.1.Scolarité, " & ",Option.facultative.2.Scolarité)
  )) %>%
  mutate(groupe.options = paste0(groupe," (", EDS.BAC.Abandonné," + ", options,")")) %>%
  group_by(groupe, options, groupe.options) %>%
  summarise(nombre = n()) %>%
  group_by(groupe) %>%
  mutate(nombre.grp = sum(nombre)) %>%
  ungroup() %>%
  mutate(
    groupe = reorder(groupe,-nombre.grp),
    groupe.options = reorder(groupe.options,nombre.grp*1000+nombre))

all <- bind_rows(
  all,
  df %>% transmute(
    bac = "Bac Blanquer",
    categorisation = "Spécialités de 1ère et Term. + options",
    categorie = groupe.options,
    nombre = nombre)
)
```

- Nombre de groupes : `r nrow(df)`
- Taille des groupes : `r range(df$nombre)`

```{r bg21.cohorte.3.plot, fig.width=10, fig.height=45}
df %>%
  ggplot(aes(groupe.options,y=nombre,fill=groupe)) +
    geom_col() +
    coord_flip() +
    scale_fill_manual(values=rev(palette_groupes)) +
    facet_grid(groupe~., scales = "free_y", space = "free_y", labeller = label_wrap_gen(width=6)) +
    xlab("Spécialités (spécialité abandonnée + options)") + ylab("Nombre de candidatures") +
    guides(fill=FALSE) +
    ggtitle("Catégorisation des candidatures avec le nouveau Bac général\n(spécialités 1ere et Terminale + options)") +
    theme_cpesr_cap() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
      )
```

### Résumé

```{r bg.sum.plot, fig.width=10, fig.height=4}
palfun <- function(x) rep(brewer.pal(3, "Paired")[1:2],x/2+1)[1:x]
allnb <- all %>% group_by(categorisation) %>% summarise(nombre = n())
palette_sum <- palfun(max(allnb$nombre))

all %>%
  mutate(categorisation = factor(categorisation, levels=rev(c("Série","Série + Spécialité","Spécialités de Terminale", "Spécialités de Terminale + options","Spécialités de Première et Terminale + options")))) %>% 
  mutate(cat = reorder(paste(categorisation,categorie),as.numeric(categorisation)*1000+nombre)) %>%
  group_by(categorisation) %>% arrange(-nombre) %>% mutate(ifill = row_number()) %>%
  ggplot(aes(x=categorisation,y=nombre, fill=as.factor(-ifill))) +
    geom_col(position="fill") +
    coord_flip() +
    scale_fill_manual(values=palette_sum) +
    scale_y_continuous(labels = scales::percent) +
    facet_grid(bac~., scales = "free_y", space = "free_y") +
    xlab("Critères de catégorisation") + ylab("Proportion des candidatures") +
    guides(fill=FALSE) +
    ggtitle("Taille des catégories comparables selon les Bacs et les critères") +
    theme_cpesr_cap() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
      )
```

## Notes 

```{r notes.1, fig.width=10, fig.height=6}
bg21 %>%
  select(Numéro,Série.Domaine.Filière, Niveau.de.la.classe, ends_with('..note.')) %>%
  pivot_longer(
    cols = ends_with('..note.'),
    names_to = "Matière",
    values_to = "Note",
    values_transform = list(Note = as.numeric),
    values_drop_na = TRUE
  ) %>%
  mutate(Matière = str_replace(Matière,"\\.\\.note\\.","")) %>%
  left_join(matieres) %>%
  mutate(Type = fct_rev(Type)) %>%
  mutate(Matière = as.factor(Matière)) %>%
  mutate(Matière = factor(Matière, labels = str_replace_all(levels(Matière),"\\."," "))) %>%

  ggplot(aes(x=reorder(Matière,Note,FUN=median),y=Note,fill=Type)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(Type~., scales = "free_y", space = "free_y") +
  xlab("Matières") + ylab("Moyennes") +
  theme_cpesr_cap() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
    )
```


```{r notes.2.data, fig.width=10, fig.height=6}
df <- bg21 %>%
  select(Numéro,Série.Domaine.Filière, Niveau.de.la.classe, starts_with('Moyenne')) %>%
  pivot_longer(
    cols = starts_with('Moyenne'),
    names_pattern = "Moyenne\\.(classe|candidat|plus.basse|plus.haute)\\.en\\.(.*)\\.Trimestre\\.(.*)",
    names_to = c("Groupe","Matière","Trimestre"),
    values_to = "Note",
    values_transform = list(Note = as.numeric),
    values_drop_na = TRUE
  ) %>%
  left_join(matieres) %>%
  mutate(Type = fct_rev(Type)) %>%
  mutate(Matière = as.factor(Matière)) %>%
  mutate(Matière = factor(Matière, labels = str_replace_all(levels(Matière),"\\."," ")))
```

```{r notes.cand.plot, fig.width=10, fig.height=8}
df %>%
  filter(Groupe == "candidat") %>%
  ggplot(aes(x=reorder(Matière,Note,FUN=median),y=Note,fill=Type)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(Type~Groupe, scales = "free_y", space = "free_y") +
  xlab("Matières") + ylab("Moyennes") +
  ylim(0,20)+
  ggtitle("Moyennes trimestrielles des candidats") +
  theme_cpesr_cap() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
    )
```


```{r notes.2.plot, fig.width=10, fig.height=8}
df %>%
  filter(Groupe == "classe") %>%
  ggplot(aes(x=reorder(Matière,Note,FUN=median),y=Note,fill=Type)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(Type~Groupe, scales = "free_y", space = "free_y") +
  xlab("Matières") + ylab("Moyennes") +
  ylim(0,20)+
  ggtitle("Moyennes trimestrielles des classes des candidats ") +
  theme_cpesr_cap() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
    )
```



```{r notes.3.plot, fig.width=10, fig.height=8}
df %>%
  filter(Groupe %in% c("plus.basse","plus.haute")) %>%
  ggplot(aes(x=reorder(Matière,Note, FUN=median),y=Note,fill=Type)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(Type~Groupe, scales = "free_y", space = "free_y") +
  xlab("Matières") + ylab("Moyennes") +
  ylim(0,20)+
  ggtitle("Moyennes trimestrielles plus basses et hautes\ndans les classes des candidats ") +
  theme_cpesr_cap() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color="grey",size=0.2),
    plot.title = element_text(hjust = 1)
    )
```


```{r notes.4.plot, fig.width=10, fig.height=3.5}
df %>%
  filter(Groupe %in% c("classe","candidat")) %>%
  filter(Matière %in% c("Numérique et Sciences Informatiques", "Mathématiques Spécialité")) %>%
  ggplot(aes(x=reorder(Matière,Note,FUN=median),y=Note,fill=Matière)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(Groupe~., scales = "free_y", space = "free_y") +
  xlab("Matières") + ylab("Moyennes") +
  ylim(0,20)+
  scale_fill_brewer(palette="Accent") +
  ggtitle("Moyennes trimestrielles des classes et des candidats en NSI et Maths ") +
  theme_cpesr_cap() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color="grey",size=0.2),
      plot.title = element_text(hjust = 1)
    )
```